version: "3"
services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./conf/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./conf/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./conf/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=passwd
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
    network_mode: host
    dns: 127.0.0.1
    # ports:
    #   - 127.0.0.1:3000:3000
  prometheus:
    image: prom/prometheus
    volumes:
      - ./conf/prometheus:/etc/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:rw
    network_mode: host
    dns: 127.0.0.1
    # ports:
    #   - 127.0.0.1:9090:9090
    user: root
  node_exporter:
    image: prom/node-exporter
    volumes:
      - /:/rootfs:ro,rslave
    pid: host
    network_mode: host
    dns: 127.0.0.1
    # ports:
    #   - 127.0.0.1:9100:9100
  cadvisor:
    image:  gcr.io/cadvisor/cadvisor:v0.38.6
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    network_mode: host
    dns: 127.0.0.1
    # ports:
    #   - 127.0.0.1:8080:8080
    privileged: true
    devices:
      - /dev/kmsg
    command: ['-docker_only', '-enable_load_reader']
  loki:
    image: grafana/loki:2.4.2
    volumes:
      - ./conf/loki:/etc/loki/
    network_mode: host
    dns: 127.0.0.1
    # ports:
    #   - 3100:3100
    command: --config.file=/etc/loki/config.yml
  promtail:
    image: grafana/promtail:2.4.2
    volumes:
      - ./conf/promtail:/etc/promtail/
      - /run/log/journal/:/journal
    network_mode: host
    command: --config.file=/etc/promtail/config.yml
    # ports:
    #   - 9080:9080
  app:
    image: my-app:latest
    build:
      context: app/
    network_mode: host
