{
 "title": "My Docker Swarm Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Swarm Node State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "swarm_manager_nodes", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Container State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Swarm Object Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "swarm_manager_services_total", "legendFormat": "services" },
    { "expr": "sum(swarm_manager_tasks_total)", "legendFormat": "tasks" },
    { "expr": "swarm_manager_secrets_total", "legendFormat": "secrets" }
   ]
  },
  {
   "title": "Container Logs Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate({job=\"systemd-journal\", unit=\"docker.service\"} |~ \"(?i)error\"[1m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Logs Warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate({job=\"systemd-journal\", unit=\"docker.service\"} |~ \"(?i)warn\"[1m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Latest Container Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", unit=\"docker.service\"} |~ \"(?i)level=error\""
    }
   ]
  },
  {
   "title": "Latest Container Warning Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\", unit=\"docker.service\"} |~ \"(?i)level=warn\""
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sort_desc((container_cpu_load_average_10s / container_spec_cpu_shares + on(name) container_cpu_load_average_10s / container_spec_cpu_shares) / 2)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "sort_desc((container_memory_usage_bytes{id=~\"^/docker.*\"} + on(name) container_memory_usage_bytes{id=~\"^/docker.*\"}) / 2) # This is X + on(..) X / 2 is simplest way I know to project a PromQL stage ..",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Swarm Task State",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "swarm_manager_tasks_total", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Container Network Rx/Tx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name, interface) > 0",
     "legendFormat": "rx-{{name}}-{{interface}}"
    },
    {
     "expr": "-(sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name, interface) > 0)",
     "legendFormat": "tx-{{name}}-{{interface}}"
    }
   ]
  },
  {
   "title": "Container CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s / container_spec_cpu_shares",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "targets": [
    { "expr": "container_memory_rss > 0", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Container Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes / container_spec_memory_limit_bytes",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(node_boot_time_seconds)" }
   ]
  },
  {
   "title": "Instance Up Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds)",
     "legendFormat": "X"
    }
   ]
  },
  {
   "title": "Filesystem Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes / node_filesystem_size_bytes",
     "legendFormat": "{{instance}}-{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "(sum(irate(node_cpu_seconds_total {mode!=\"idle\"} [1m])) without (cpu)) / count(node_cpu_seconds_total) without (cpu)",
     "legendFormat": "{{instance}}-{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network RX/TX (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"^(veth|dummy|br).*\",device!~\".*(bridge|docker).*\"}[1m]) / 1000   ",
     "legendFormat": "rx-{{instance}}-{{device}}"
    },
    {
     "expr": "- rate(node_network_transmit_bytes_total{device!~\"^(veth|dummy|br).*\",device!~\".*(bridge|docker).*\"}[1m]) / 1000   ",
     "legendFormat": "tx-{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "HDD R/W (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m]) / 1000",
     "legendFormat": "read-{{instance}}-{{device}}"
    },
    {
     "expr": "- rate(node_disk_written_bytes_total[1m]) / 1000",
     "legendFormat": "write-{{instance}}-{{device}}"
    }
   ]
  },
  {
   "title": "Prometheus Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{quantile}} ({{interval}})"
    }
   ]
  },
  {
   "title": "Prometheus Target Scrapes (last 5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Prometheus Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\"})"
    }
   ]
  },
  { "title": "Cluster Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } }
 ]
}