groups:
- name: cpu-node
  rules:
  - record: job_instance_mode:node_cpu_seconds:avg_rate5m
    expr: avg by (job, instance, mode) (rate(node_cpu_seconds_total[5m]))
- name: containers
  rules:
  - record: container:was_running
    expr: sort_desc(time() - timestamp(container_tasks_state{state="running"}) < 15)
